### ISSUE TITLE
Fix CI issues

### ISSUE THREAD

**Issue by theoutlander** [theoutlander/testerbot#9]
#!/bin/bash -eo pipefail
npm test

> testerbot@0.0.1 test /home/circleci/repo
> concurrently 'npm run static' 'jest --config ./src/jest.config.js'

[0] 
[0] > testerbot@0.0.1 static /home/circleci/repo
[0] > static ./tests -H '{"Cache-Control": "no-cache, must-revalidate"}'  &
[0] 
[0] serving "./tests" at http://127.0.0.1:8080
[1] Setup Puppeteer Environment.
[1] Error: kill ESRCH
[1]     at Object._errnoException (util.js:1024:11)
[1]     at process.kill (internal/process.js:183:18)
[1]     at forceKillChrome (/home/circleci/repo/node_modules/puppeteer/lib/Launcher.js:162:19)
[1]     at killChrome (/home/circleci/repo/node_modules/puppeteer/lib/Launcher.js:147:9)
[1]     at Function.launch (/home/circleci/repo/node_modules/puppeteer/lib/Launcher.js:137:7)
[1]     at <anonymous>
[1]     at process._tickCallback (internal/process/next_tick.js:188:7)
[1] jest --config ./src/jest.config.js exited with code 1
Too long with no output (exceeded 10m0s)

**Comment by theoutlander** [comment]
Disabled tests for now and opened issue on https://github.com/GoogleChrome/puppeteer/issues/1700

**Comment by theoutlander** [comment]
Have tried the following with no luck: 

```
args: ['--no-sandbox', '--disable-setuid-sandbox']
```

**Comment by theoutlander** [comment]
Need to try suggestions listed in https://github.com/GoogleChrome/puppeteer/issues/290

**Comment by esperancaJS** [comment]
did you solve this?

**Comment by theoutlander** [comment]
Yes, I think I had solved it. It's been a while, so I don't recall what I did exactly as Puppeteer has evolved quite a bit. I think I followed the suggestions in that referenced issue.

**Comment by esperancaJS** [comment]
My issue was solved by using a more recent prebuilt docker image (using CircleCI)
